### ISSUE TITLE
Add predetermined district seat numbers to the API

### ISSUE THREAD

**Issue by Log234** [Project-Lavinia/Lavinia-api#13]
The new API should also support returning predetermined district seat numbers for elections before 2005, where these were not calculated based on population and area.
It should be handled in a way so that you always return values for both area factor and predetermined seat numbers. But in the case where the seat numbers are calculated, the predetermined seats should be listed as 0. And when the seat numbers are predetermined area factor should be a big negative number, preferably -inf if possible, otherwise -999. This makes it easy to check for and still allows for plausible but unlikely situations where the area factor might actually be 0.

**Comment by simendag** [comment]
There should be a function/ruleset that takes an election year and returns the appropriate data for seats, including distributions among districts, levelling seats, etc. On the client-side this can be parsed/handled based on data types and what is/is not there.
